version: "3.9"

networks:
  npos_network:
    name: npos_network
    ipam:
      config:
        - subnet: 172.29.0.0/16
services:
# ============================== Database ==============================
  npos_db:
    container_name: npos_db
    image: postgres:14.1
    networks:
      npos_network:
        ipv4_address: 172.29.0.2
    restart: always
    ports:
      - '5290:5432'
    volumes:
            - ./main_db/db:/var/lib/postgresql/data
            - ./main_db/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=20002000

# ============================== Redis ==============================
  npos_redis:
    container_name: npos_redis
    image: redis:7.0.7-alpine
    networks:
      npos_network:
        ipv4_address: 172.29.0.3
    restart: always
    expose:
      - 6379
# ============================== Rust ==============================
  npos_service:
    container_name: npos_service
    image: env_rust_container:latest
    networks:
      npos_network:
        ipv4_address: 172.29.0.5
    # restart: always
    ports:
      - 3300:3000
    volumes:
      - ./app:/app/
    depends_on:
      - npos_db
      - npos_redis
    command: sleep infinity
